export const FETCH_ALL_ITEMS = "FETCH_ALL_ITEMS";
export const FETCH_ITEMS = "FETCH_ITEMS";
export const ADD_ITEMS = "ADD_ITEMS";
export const UPDATE_ITEMS = "UPDATE_ITEMS";
export const DELETE_ITEMS = "UPDATE_ITEMS";
export const FETCH_ITEMS_CATEGORY = "FETCH_ITEMS_CATEGORY";
